In [1]:
import numpy as np

In [2]:
# Additional 1

a = np.random.randint(30, 40, 10)

print(a)

[38 30 34 37 34 31 37 36 37 33]


In [3]:
# Additional 2

A = np.array(((1, 2, 3), (4, 5, 6), (7, 8, 10)))
B = np.array(((7, 8, 10) ,(4, 5, 6), (1, 2, 3)))

# i.
C = A + B
E = A - B

print('A + B : ')
print(C)

print('\nA - B: ')
print(E)

# ii.
print(f'\nSum of all elements in A: {A.sum()}')
print(f'Sum of each columns in B: {B.sum(0)}')
print(f'Sum of each row in C: {C.sum(1)}')

# iii.
D = A.dot(B)

print('\nA * B: ')
print(D)

# iv.
C.sort()

print('\nSorted matrix C: ')
print(C)

# v.
print('\nE Transpose: ')
print(E.T)

A + B : 
[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]

A - B: 
[[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]

Sum of all elements in A: 46
Sum of each columns in B: [12 15 19]
Sum of each row in C: [31 30 31]

A * B: 
[[ 18  24  31]
 [ 54  69  88]
 [ 91 116 148]]

Sorted matrix C: 
[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]

E Transpose: 
[[-6  0  6]
 [-6  0  6]
 [-7  0  7]]
