In [1]:
import numpy as np

In [2]:
# Exercise 1

a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

b = a.reshape((3, 3))

print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [3]:
# Exercise 2

a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

a[a%2 == 1] = -1

print(a)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [4]:
# Exercise 3

x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

greater = np.where(x > y)
equals = np.where(x == y)

print('x greater than y: ', greater)
print('x equals y: ', equals)

x greater than y:  (array([1, 2, 4, 5, 6, 7, 8, 9]),)
x equals y:  (array([0]),)


In [5]:
# Exercise 4

a = np.arange(100).reshape(5,-1)

print(a[:, :4])

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]
