In [1]:
import csv

In [2]:
with open('data.csv', 'r') as f:
    reader = csv.reader(f)
    for row in reader:
        print(row)

['Programming language', 'Designed by', 'Appeared', 'Extension']
['Python', 'Guido van Rossum', '1991', '.py']
['Java', 'James Gosling', '1995', '.java']
['C++', 'Bjarne Stroustrup', '1983', '.cpp']


In [3]:
with open('data.csv', 'rt') as f:
    reader = csv.DictReader(f)
    for raw in reader:
        print(raw)

{'Programming language': 'Python', 'Designed by': 'Guido van Rossum', 'Appeared': '1991', 'Extension': '.py'}
{'Programming language': 'Java', 'Designed by': 'James Gosling', 'Appeared': '1995', 'Extension': '.java'}
{'Programming language': 'C++', 'Designed by': 'Bjarne Stroustrup', 'Appeared': '1983', 'Extension': '.cpp'}


In [4]:
with open('data1.csv', 'w') as f:
    writer = csv.writer(f, delimiter=',')
    writer.writerow(['Programming Language', 'Designed by', 'Appeared', 'Extension'])
    writer.writerow(['Python', 'Guido van Rossum', '1991', '.py'])
    writer.writerow(['Java', 'James Gosling', '1995', '.java'])
    writer.writerow(['C++', 'Bjarne Stroustrup', '1983', '.cpp'])

In [5]:
import pandas as pd

In [6]:
result = pd.read_csv('data1.csv')

print(result)

  Programming Language        Designed by  Appeared Extension
0               Python   Guido van Rossum      1991       .py
1                 Java      James Gosling      1995     .java
2                  C++  Bjarne Stroustrup      1983      .cpp


In [7]:
from pandas import DataFrame

In [8]:
C = {'Programming Language': ['Python', 'Java', 'C++'], 
     'Designed by': ['Guido van Rossum', 'James Gosling', 'Bjarne Stroustrup'],
     'Appeared': ['1991', '1995', '1983'], 
     'Extension': ['.py', '.java', '.cpp']}

In [9]:
df = DataFrame(C, columns=C.keys())

export_csv = df.to_csv('data2.csv', index=False, header=True)

In [10]:
print(df)

  Programming Language        Designed by Appeared Extension
0               Python   Guido van Rossum     1991       .py
1                 Java      James Gosling     1995     .java
2                  C++  Bjarne Stroustrup     1983      .cpp


In [11]:
import numpy as np

In [12]:
a = np.arange(15).reshape(3, 5)

a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
a.shape

(3, 5)

In [14]:
a.ndim

2

In [15]:
a.dtype.name

'int64'

In [16]:
a.itemsize

8

In [17]:
a.size

15

In [18]:
type(a)

numpy.ndarray

In [19]:
b = np.array([6, 7, 8])

b

array([6, 7, 8])

In [20]:
type(b)

numpy.ndarray

In [21]:
a = np.array([2, 3, 4])

a

array([2, 3, 4])

In [22]:
a.dtype

dtype('int64')

In [23]:
b = np.array([1.2, 3.5, 5.1])

b.dtype

dtype('float64')

In [24]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])

b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [25]:
c = np.array([[1, 2], [3, 4]], dtype='complex')

c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [26]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [28]:
np.empty((2, 3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [29]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [30]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [31]:
from numpy import pi

In [32]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [33]:
x = np.linspace(0, 2*pi, 100)

In [34]:
f = np.sin(x)

In [35]:
a = np.arange(6)

In [36]:
print(a)

[0 1 2 3 4 5]


In [37]:
b = np.arange(12).reshape(4, 3)

In [38]:
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [39]:
c = np.arange(24).reshape(2, 3, 4)

In [40]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [41]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [42]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [43]:
a = np.array([20, 30, 40, 50])

b = np.arange(4)

In [44]:
b

array([0, 1, 2, 3])

In [45]:
c = a-b

In [46]:
c

array([20, 29, 38, 47])

In [47]:
b**2

array([0, 1, 4, 9])

In [48]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [49]:
a < 35

array([ True,  True, False, False])

In [50]:
A = np.array([[1, 1],
              [0, 1]])

In [51]:
B = np.array([[2, 0],
              [3, 4]])

In [52]:
A * B

array([[2, 0],
       [0, 4]])

In [53]:
A @ B

array([[5, 4],
       [3, 4]])

In [54]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [55]:
rg = np.random.default_rng(1)

In [56]:
a = np.ones((2, 3), dtype=int)

b = rg.random((2, 3))

In [57]:
a *= 3

In [58]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [59]:
b += a

In [60]:
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [61]:
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [62]:
a = np.ones(3, dtype=np.int32)

b = np.linspace(0, pi, 3)

In [63]:
b.dtype.name

'float64'

In [64]:
c = a + b

In [65]:
c

array([1.        , 2.57079633, 4.14159265])

In [66]:
c.dtype.name

'float64'

In [67]:
d = np.exp(c * 1j)

In [68]:
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [69]:
d.dtype.name

'complex128'

In [70]:
a = rg.random((2, 3))

In [71]:
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [72]:
a.sum()

3.1057109529998157

In [73]:
a.min()

0.027559113243068367

In [74]:
a.max()

0.8277025938204418